### ISSUE TITLE
Genome mapper

### ISSUE THREAD

**Issue by curtisim0** [TAMU-CPT/CPT-ToolshedSource#10]
Fix the "linear genome plot" tool

**Comment by jasonjgill** [comment]
Error message when I tried to run Linear Genome Plot:

Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/linear_genome_plot.py", line 3, in <module>
    from dna_features_viewer import BiopythonTranslator, GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/__init__.py", line 3, in <module>
    from .GraphicRecord import GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/__init__.py", line 1, in <module>
    from .GraphicRecord import GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/GraphicRecord.py", line 9, in <module>
    from .BokehPlottableMixin import BokehPlottableMixin
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/BokehPlottableMixin.py", line 10, in <module>
    import pandas as pd
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/pandas/__init__.py", line 180, in <module>
    import pandas.testing
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/pandas/testing.py", line 5, in <module>
    from pandas._testing import (
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/pandas/_testing.py", line 24, in <module>
    import pandas._libs.testing as _testing
  File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by jasonjgill** [comment]
Bjorn says the tool should be updated but when I tested it i got a similar error as before:

Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/linear_genome_plot.py", line 3, in <module>
    from dna_features_viewer import BiopythonTranslator, GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/__init__.py", line 3, in <module>
    from .GraphicRecord import GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/__init__.py", line 1, in <module>
    from .GraphicRecord import GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/GraphicRecord.py", line 9, in <module>
    from .BokehPlottableMixin import BokehPlottableMixin
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/BokehPlottableMixin.py", line 10, in <module>
    import pandas as pd
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/pandas/__init__.py", line 180, in <module>
    import pandas.testing
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/pandas/testing.py", line 5, in <module>
    from pandas._testing import (
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/pandas/_testing.py", line 24, in <module>
    import pandas._libs.testing as _testing
  File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
  File "/usr/local/tools/_conda/envs/mulled-v1-8de2d0da844e361b56c1dfd483800bfb038c8ce53b2199ddbf35b15cec318162/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by curtisim0** [comment]
Let me double check, but that should no longer be the case. Smells like cache.

**Comment by curtisim0** [comment]
Okay, I did a "resync" as I had a small diff on local. But, I do believe it is a caching thing or something. There's no mentions of `pandas` in this tool, besides a deep dependency that try/excepts to see if it's available.

IE, this error can't be raised **unless** it's pulling a previous version/sha (from what I can tell).

**Comment by jasonjgill** [comment]
Is caching even a thing in the toolshed? I will ask Bjorn to run the update from the toolshed again.

**Comment by jasonjgill** [comment]
ran it again got a different error:

Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/linear_genome_plot.py", line 3, in <module>
    from dna_features_viewer import BiopythonTranslator, GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/__init__.py", line 3, in <module>
    from .GraphicRecord import GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/__init__.py", line 1, in <module>
    from .GraphicRecord import GraphicRecord
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/GraphicRecord.py", line 16, in <module>
    from .MatplotlibPlottableMixin import MatplotlibPlottableMixin
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/cpt/cpt_linear_genome_plot/e923c686ead9/cpt_linear_genome_plot/dna_features_viewer/GraphicRecord/MatplotlibPlottableMixin.py", line 5, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by curtisim0** [comment]
hmmmm matplotlib is part of the dependencies.

Can you confirm that the dependencies are resolved on the eu galaxy?
